FROM microsoft/dotnet:2.0-sdk AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# copy and build everything else
COPY . ./
RUN dotnet publish -c Release -o out

EXPOSE 5000/tcp
ENTRYPOINT ["dotnet", "out/Livraria.Api.dll"]
